services:
  - type: web
    name: securinets-crackme
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_db.py && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 60 app:app"
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
